import {continentalStandingsView} from './continental-standings-view.mjs';
import {regionalStandingsView} from './regional-standings-view.mjs';
import {initialStandingsState} from './standings-data.mjs';import {leagueStandingsView} from './standings-view.mjs';import {UnportedOperationError} from './ui-surface.mjs';
export function createStandingsHost(renderer,{save,language,crestAssets,subgroupOverride=-1,showCompetition}){
 let active=null,opening=false,revision=0;
 async function prepare(frame){const form=renderer.forms.get('Form36'),paths=form.children.filter(n=>n.class_name==='TImage').map(n=>n.properties['Picture.Data']?.asset);await Promise.all([...new Set([frame.background,...paths,...frame.standingsTables.flatMap(t=>t.rows.map(r=>r.crest))].filter(Boolean))].map(p=>renderer.bitmap(p)));}
 function close(){if(!active||renderer.frame?.form!=='Form36')return false;const pending=active;active=null;revision++;renderer.close();pending.resolve();return true;}
 async function league(division=1,leagueId=active?.state.leagueId){if(!active)return;const token=++revision,state={...active.state,competition:1,leagueId,division},previous=renderer.frame?.form==='Form36'&&leagueId===active.state.leagueId&&active.state.competition===1?renderer.frame:null,frame=leagueStandingsView(save,state,language,crestAssets,previous);await prepare(frame);if(!active||revision!==token)return;active.state=state;renderer.update(frame);}
 async function regional(lowerDivisions=false,subgroup=active?.state.subgroup){if(!active)return;const token=++revision,state={...active.state,competition:3,subgroup,lowerDivisions},frame=regionalStandingsView(save,state,language,crestAssets);await prepare(frame);if(!active||revision!==token)return;active.state=state;renderer.update(frame);}
 async function competition(kind,stage){if(!active)return;if(kind===3)return regional();if([4,6].includes(kind)){const token=++revision,state={...active.state,competition:kind,stage,selectedImage:kind===6?5:[4,3,6,7][stage]},frame=continentalStandingsView(save,state,language,crestAssets,renderer.frame);await prepare(frame);if(!active||revision!==token)return;active.state=state;renderer.update(frame);return;}if(!showCompetition)throw new UnportedOperationError('Form36 competition '+kind+' stage '+stage);return showCompetition({kind,stage,state:active.state});}
 const keydown=e=>{if(active&&renderer.frame?.form==='Form36'&&e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();close();}};document.addEventListener('keydown',keydown,true);
 renderer.register('Form36.combo1Change',index=>regional(false,renderer.frame.regions[index].subgroup));renderer.register('Form36.Image12Click',()=>regional(true));
 renderer.register('Form36.Image8Click',close);renderer.register('Form36.Button1Click',close);renderer.register('Form36.Image1Click',()=>league(1));renderer.register('Form36.combopaisChange',index=>league(1,index));
 for(let i=0;i<3;i++)renderer.register('Form36.Image'+(9+i)+'Click',()=>league(i+2));
 for(const [image,kind,stage] of [[2,3,0],[3,4,1],[4,4,0],[5,6,1],[6,4,2],[7,4,3]])renderer.register('Form36.Image'+image+'Click',()=>competition(kind,stage));
 async function open(){if(active||opening)throw Error('Standings already open.');opening=true;try{const state=initialStandingsState(save,{subgroupOverride});if(![1,3,4,6].includes(state.competition)){if(!showCompetition)throw new UnportedOperationError('Form36 initial competition '+state.competition);return showCompetition({kind:state.competition,stage:0,state});}const frame=[4,6].includes(state.competition)?continentalStandingsView(save,state,language,crestAssets):state.competition===3?regionalStandingsView(save,state,language,crestAssets):leagueStandingsView(save,state,language,crestAssets);await prepare(frame);const result=new Promise(resolve=>{active={state,resolve};});await renderer.show(frame,{modal:true});renderer.canvas.focus();return result;}finally{opening=false;}}
 return {open,close,league,regional,competition,get active(){return active;},snapshot:()=>active?{...active.state,brackets:renderer.frame?.regionalBrackets?.filter(p=>p.visible).map(p=>({stage:p.stage,title:p.title,rows:p.rows})),tables:renderer.frame?.standingsTables?.filter(t=>t.visible!==false).map(t=>({division:t.division,group:t.group,rows:t.rows.map(r=>({clubId:r.clubId,rank:r.rank,cells:r.cells,color:r.color}))}))}:null,dispose:()=>document.removeEventListener('keydown',keydown,true)};
}
