"""Recover the literal scheduling sequence; original-instruction vectors verify it."""
from pathlib import Path
import re
R=Path(__file__).resolve().parents[1]
s=(R/'decompiled/00653a40_FUN_00653a40.c').read_text();s=s[s.index('  if (*(int *)(PTR_DAT_0066ac78 + 0x168) == 2)'):];s=s[:s.rfind('  return;')]
s=s.replace('*(int *)(PTR_DAT_0066ac78 + 0x168)','mode').replace('FUN_006539b4','put').replace('cVar1 = FUN_006500c8();','cupExtra = hasExtraCupRound(mode,cupRecords);').replace("cVar1 == '\\0'",'!cupExtra').replace("cVar1 != '\\0'",'cupExtra')
for a,b in [('uVar3','c3'),('uVar2','c4'),('local_28','c2'),('local_24','c5'),('local_20','c6'),('local_1c','national'),('local_14','c10')]:s=s.replace(a,b)
s=s.replace('hasExtraCupRound(mode,cupRecords)','hasExtraCupRound()')
header='// Recovered literal sequence from 00653a40; generated by export_schedule_port.py.\nexport function originalScheduleSequence({mode,c2,c3,c4,c5,c6,c10,national,hasExtraCupRound,put}){\n let cupExtra;\n'
(R.parent/'cyberfoot-web/native-port/schedule-sequence.mjs').write_text(header+s+'}\n')
