import {chromium} from 'playwright';import assert from 'node:assert/strict';import {writeFileSync} from 'node:fs';
import {testOutputFile} from './browser-test-helpers.mjs';
const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1024,height:768}}),errors=[];page.on('pageerror',e=>errors.push(String(e)));
await page.goto('http://127.0.0.1:8766/lineup-window-preview.html');await page.waitForFunction(()=>window.lineupDevelopment);
await page.locator('[data-original-control="Form87.rd2"]').check();const state=JSON.parse(await page.evaluate(()=>window.render_game_to_text()));assert.equal(state.selectedKit,2);assert.equal(state.checkedKit,2);
const saved=await page.evaluate(async()=>{const {readSave,record}=await import('./save-format.mjs');const save=readSave(window.lineupDevelopment.save()),bytes=record(save,'clubs',11);return new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength).getInt32(0x2e8,true);});assert.equal(saved,2);
assert.equal(await page.locator('[data-original-control="Form87.rd3"]').isVisible(),false);
await page.screenshot({path:testOutputFile('native-lineup-kits','away.png')});
await page.locator('[data-original-control="Form87.rd1"]').check();assert.equal(JSON.parse(await page.evaluate(()=>window.render_game_to_text())).selectedKit,1);
await page.goto('http://127.0.0.1:8766/match-window-preview.html?tacticsIntegration=1');await page.waitForFunction(()=>window.beginTacticsCheck);await page.evaluate(()=>window.beginTacticsCheck());await page.waitForFunction(()=>window.tacticsDevelopment.renderer.frame.form==='Form88');
const initial=JSON.parse(await page.evaluate(()=>window.render_game_to_text())).tactics;assert.match(initial.shirtPath,/kits\/camisas\//);
await page.evaluate(()=>{const d=window.tacticsDevelopment;d.state.clubs[d.fixture.clubs[1]].kitColour=d.state.clubs[d.fixture.clubs[0]].kitColour;d.renderer.invoke({operation:'nometime2Click'});});
const away=JSON.parse(await page.evaluate(()=>window.render_game_to_text())).tactics;assert.equal(away.selectedKit,2);assert.match(away.shirtPath,/kits\/camisas2\//);await page.screenshot({path:testOutputFile('native-match-kits','away-clash.png')});
await page.evaluate(()=>{const d=window.tacticsDevelopment;d.state.clubs[d.fixture.clubs[0]].selectedKit=3;d.renderer.invoke({operation:'nometime1Click'});});const third=JSON.parse(await page.evaluate(()=>window.render_game_to_text())).tactics;assert.equal(third.selectedKit,3);assert.match(third.shirtPath,/kits\/camisas3\//);await page.screenshot({path:testOutputFile('native-match-kits','third.png')});
writeFileSync(testOutputFile('native-match-kits','checks.json'),JSON.stringify({savedKit:saved,initial,away,third,errors},null,2));await browser.close();assert.deepEqual(errors,[]);console.log('Original kits in browser: pre-match selection/save, hidden absent third kit, AI colour-clash kit2, human kit3 passed.');
