import assert from 'node:assert/strict';import fs from 'node:fs';
import {readSave,writeSave} from '../save-format.mjs';
import {listChampionshipCountries,selectChampionshipClubs,buildCustomChampionship,simulateCustomCupRound,simulateCustomLeagueRound,championshipView,CHAMPIONSHIP_FORMATS,CUSTOM_CLUB_LIMIT} from '../championship.mjs';
import {resolveTwoLegResult} from '../knockout-result.mjs';
const saveBytes=fs.readFileSync(new URL('./original-career.s15',import.meta.url)),language=JSON.parse(fs.readFileSync(new URL('../language.json',import.meta.url)));
const save=readSave(saveBytes),before=writeSave(save);
const countries=listChampionshipCountries(save,{language});
assert.ok(countries.length>4,'Form39 lists several countries');
assert.ok(countries.every((entry)=>entry.count>0),'only countries with clubs are listed');
const picked=[countries[0].country,countries[1].country];
const clubIds=selectChampionshipClubs(save,picked);
assert.ok(clubIds.length>0,'selection returns clubs');
assert.ok(clubIds.length<=CUSTOM_CLUB_LIMIT,'1000-club cap holds');
const cup=buildCustomChampionship({clubIds:clubIds.slice(0,8),formatId:'4x10',playCup:true,seed:2015});
assert.equal(cup.formatId,'4x10');
assert.equal(cup.mode,4);
assert.equal(cup.groups.length,1,'8 clubs fit one 10-team division');
assert.equal(cup.cupBracket.length,4,'8 clubs pair into 4 ties');
assert.equal(cup.totalClubs,8);
const league20=buildCustomChampionship({clubIds:clubIds.slice(0,8),formatId:'2x20',playCup:false,seed:7});
assert.equal(league20.mode,2);
assert.equal(league20.cupBracket,null,'cup disabled returns null bracket');
assert.equal(CHAMPIONSHIP_FORMATS[0].languageId,13);
const first=simulateCustomCupRound(save,cup.cupBracket,{seed:42});
assert.equal(first.winners.length,4,'one cup round yields 4 winners');
const replay=simulateCustomCupRound(save,cup.cupBracket,{seed:42});
assert.deepEqual(replay,first,'cup simulation is deterministic');
const explicit=simulateCustomCupRound(save,[[clubIds[0],clubIds[1]]],{scores:[{firstLeg:[2,0],secondLeg:[1,1]}]});
assert.equal(explicit.winners[0],clubIds[0],'2-0/1-1 advances the home club via 0061edd0');
assert.equal(resolveTwoLegResult({firstLeg:[2,0],secondLeg:[1,1],competition:2}),1);
const table=simulateCustomLeagueRound(clubIds.slice(0,4),{seed:9});
assert.equal(table.length,4);
assert.ok(table.every((row)=>row.played===3),'4-team single round robin plays 3 each');
assert.deepEqual(simulateCustomLeagueRound(clubIds.slice(0,4),{seed:9}),table,'league simulation is deterministic');
const view=championshipView({language,countries,selectedCountries:picked,formatId:'4x10',playCup:true,registered:true,totalClubs:clubIds.length});
assert.equal(view.form,'Form39');
assert.equal(view.continueEnabled,true);
assert.equal(view.formatEnabled,true);
assert.deepEqual(writeSave(save),before,'championship setup leaves the real save untouched');
console.log(`Championship Form39: ${String(countries.length)} countries, ${String(clubIds.length)} clubs for [${String(picked)}], cup 8->${String(first.winners.length)} winners deterministic, league 4-team round robin ok.`);
