import assert from 'node:assert/strict';import fs from 'node:fs';
import {readSave,writeSave} from '../save-format.mjs';
import {isRegistered,validateRegistrationKey,deriveForm42Code,deriveStartupCode,applyRegistration,clearRegistration,readRegistration,registrationView,REGISTRATION_FLAG_OFFSET} from '../registration.mjs';
const saveBytes=fs.readFileSync(new URL('./original-career.s15',import.meta.url)),language=JSON.parse(fs.readFileSync(new URL('../language.json',import.meta.url)));
const fresh=()=>readSave(saveBytes),view=(bytes)=>new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);
assert.equal(isRegistered(500),true,'00651f8c gate registers above 499');
assert.equal(isRegistered(499),false,'00651f8c gate rejects 499');
assert.equal(isRegistered(0),false);
const viewModel=registrationView({language});
assert.equal(viewModel.form,'Form42');
assert.equal(viewModel.nameLabel,language[778].text);
assert.equal(viewModel.codeLabel,language[779].text);
assert.equal(viewModel.submitLabel,language[780].text);
assert.ok(viewModel.benefits.includes(language[769].text));
const validName='M Steen 77';
const validCode=deriveForm42Code(validName);
assert.equal(validateRegistrationKey({name:validName,code:validCode}).valid,true,'Form42 length branch accepts derived code');
assert.equal(validateRegistrationKey({name:validName,code:'1000'}).valid,false,'wrong code rejected');
assert.equal(validateRegistrationKey({name:'Crackx',code:validCode}).valid,false,'crack name rejected');
assert.equal(validateRegistrationKey({name:'AB',code:'8256'}).valid,false,'short name rejected');
assert.equal(validateRegistrationKey({name:validName,code:'ABCD'}).valid,false,'non-numeric code rejected');
const startupName='John Doe';
const startupCode=deriveStartupCode(startupName);
assert.equal(validateRegistrationKey({name:startupName,code:startupCode}).valid,true,'startup weighted branch accepts derived code');
const save=fresh();
const applied=applyRegistration(save,{name:validName,code:validCode});
assert.equal(applied.valid,true);
assert.equal(applied.registered,true);
assert.equal(readRegistration(save).registered,true);
assert.ok(view(save.career).getInt32(REGISTRATION_FLAG_OFFSET,true)>499);
assert.deepEqual(readSave(writeSave(save)).career[REGISTRATION_FLAG_OFFSET],save.career[REGISTRATION_FLAG_OFFSET],'registration flag round-trips');
const replay=()=>{const target=fresh();applyRegistration(target,{name:validName,code:validCode});return writeSave(target);};
assert.deepEqual(replay(),writeSave(save),'registration apply is deterministic');
const invalidSave=fresh();
const rejected=applyRegistration(invalidSave,{name:validName,code:'1000'});
assert.equal(rejected.valid,false);
assert.equal(readRegistration(invalidSave).registered,false);
const cleared=clearRegistration(save);
assert.equal(cleared.registered,false);
assert.equal(view(save.career).getInt32(REGISTRATION_FLAG_OFFSET,true),0);
console.log(`Registration Form42: gate 00651f8c >499, valid ${validName}/${validCode} registered=${applied.flag}, startup ${startupName}/${startupCode} ok, invalid rejected, clear ok.`);
