import assert from 'node:assert/strict';import fs from 'node:fs';
import {readSave,writeSave} from '../save-format.mjs';
import {isRegistered,validateRegistrationKey,deriveForm42Code,deriveStartupCode,transformFinalName,liveExpectedCode,form42LengthBranch,isBlacklistedName,applyRegistration,clearRegistration,readRegistration,registrationView,REGISTRATION_FLAG_OFFSET} from '../registration.mjs';
const saveBytes=fs.readFileSync(new URL('./original-career.s15',import.meta.url)),language=JSON.parse(fs.readFileSync(new URL('../language.json',import.meta.url)));
const fresh=()=>readSave(saveBytes),view=(bytes)=>new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);
assert.equal(isRegistered(500),true,'00651f8c gate registers above 499');
assert.equal(isRegistered(499),false,'00651f8c gate rejects 499');
assert.equal(isRegistered(0),false);
const viewModel=registrationView({language});
assert.equal(viewModel.form,'Form42');
assert.equal(viewModel.nameLabel,language[778].text);
assert.equal(viewModel.codeLabel,language[779].text);
assert.equal(viewModel.submitLabel,language[780].text);
assert.ok(viewModel.benefits.includes(language[769].text));
const validName='M Steen 77';
const validCode=deriveForm42Code(validName);
assert.equal(validateRegistrationKey({name:validName,code:validCode}).valid,true,'Form42 LIVE 005b6ad0:0x3c accepts derived code');
assert.equal(validateRegistrationKey({name:validName,code:validCode}).reason,'form42-live','live reason');
assert.equal(transformFinalName(validName),transformFinalName(validName),'transform deterministic');
assert.ok(liveExpectedCode(transformFinalName(validName))===Number(validCode),'live expected matches derive');
assert.equal(validateRegistrationKey({name:validName,code:String(validName.length*0x408)}).valid,false,'DEAD length*0x408 branch rejected (flag 0x31 never read; only 0x3c at 0x5b8071 gates)');
assert.equal(form42LengthBranch(validName,String(10*77*0x408)),true,'dead length helper computes len*byte0*0x408 (10*77*1032=794640, not accepted)');
assert.equal(validateRegistrationKey({name:validName,code:'1000'}).valid,false,'wrong code rejected');
assert.equal(validateRegistrationKey({name:'Crackx',code:validCode}).valid,false,'crack name rejected');
assert.equal(isBlacklistedName('Emmanuel Dos Santos'),true,'blacklist 00647cec normalizes to emmanueldossantos');
assert.equal(validateRegistrationKey({name:'Emmanuel Dos Santos',code:deriveForm42Code('Emmanuel Dos Santos')}).valid,false,'blacklisted name rejected even with correct hash (005b807e)');
assert.equal(validateRegistrationKey({name:'AB',code:'8256'}).valid,false,'short name rejected');
assert.equal(validateRegistrationKey({name:validName,code:'ABCD'}).valid,false,'non-numeric code rejected');
const startupName='John Doe';
const startupCode=deriveStartupCode(startupName);
assert.equal(validateRegistrationKey({name:startupName,code:startupCode}).valid,true,'startup LIVE 0064aa20 accepts derived code');
const save=fresh();
const beforeRef=Buffer.from(fresh().career.subarray(0x700,0x740));
const beforeTail=Buffer.from(fresh().career.subarray(0x744,0x760));
const applied=applyRegistration(save,{name:validName,code:validCode});
assert.equal(applied.valid,true);
assert.equal(applied.registered,true);
assert.equal(readRegistration(save).registered,true);
assert.ok(view(save.career).getInt32(REGISTRATION_FLAG_OFFSET,true)>499);
assert.deepEqual(Buffer.from(save.career.subarray(0x700,0x740)),beforeRef,'registration mirror career+0x740 does not touch referee ids 0x700-0x738 (oracle: no 0x740 refs, sentinel preserved across 005df914)');
assert.deepEqual(Buffer.from(save.career.subarray(0x744,0x760)),beforeTail,'registration mirror career+0x740 does not touch season flags 0x75c/0x75d (0x739-0x75b zero in template)');
assert.deepEqual(readSave(writeSave(save)).career[REGISTRATION_FLAG_OFFSET],save.career[REGISTRATION_FLAG_OFFSET],'registration flag round-trips');
const replay=()=>{const target=fresh();applyRegistration(target,{name:validName,code:validCode});return writeSave(target);};
assert.deepEqual(replay(),writeSave(save),'registration apply is deterministic');
const invalidSave=fresh();
const rejected=applyRegistration(invalidSave,{name:validName,code:'1000'});
assert.equal(rejected.valid,false);
assert.equal(readRegistration(invalidSave).registered,false);
const cleared=clearRegistration(save);
assert.equal(cleared.registered,false);
assert.equal(view(save.career).getInt32(REGISTRATION_FLAG_OFFSET,true),0);
console.log(`Registration Form42: gate 00651f8c >499, valid ${validName}/${validCode} registered=${applied.flag}, startup ${startupName}/${startupCode} ok, invalid rejected, clear ok.`);
